[tool.isort]
profile = "django"
combine_as_imports = true
include_trailing_comma = true
line_length = 79
extend_skip = ["migrations"]
known_first_party = ["api", "core"]
no_lines_before = ["LOCALFOLDER"]