# Generated by Django 4.2.10 on 2024-02-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="question",
            name="game",
        ),
        migrations.AddField(
            model_name="game",
            name="questions",
            field=models.ManyToManyField(to="core.question"),
        ),
        migrations.AddField(
            model_name="question",
            name="answers",
            field=models.ManyToManyField(to="core.answer"),
        ),
    ]
