# Generated by Django 4.2.10 on 2024-02-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_answer_question_remove_question_game_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="questions",
            field=models.ManyToManyField(null=True, to="core.question"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answers",
            field=models.ManyToManyField(null=True, to="core.answer"),
        ),
    ]
