# Generated by Django 4.2.10 on 2024-02-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_game_questions_alter_question_answers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="questions",
            field=models.ManyToManyField(blank=True, null=True, to="core.question"),
        ),
        migrations.AlterField(
            model_name="question",
            name="answers",
            field=models.ManyToManyField(blank=True, null=True, to="core.answer"),
        ),
    ]
